peoplemanagement/blog/urls.py
from django.urls  import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.PostList, name='home'),
    url(r'^post/new/$', views.PostCreate, name='post-new'),
    url(r'^post/user/(?P<username>[\w-]+)/$', views.PostUserList, name='post-user-list'),
    url(r'^post/category/(?P<slug>[\w-]+)/$', views.PostCategoryList, name='post-category-list'),
    url(r'^post/(?P<slug>[\w-]+)/$', views.PostDetail, name='post-detail'),
    url(r'^invalid/$', views.Permission, name='permission-page'),
    # url(r'^admin/?P<slug>[\w-]+)/$', views.PostCreate, name='post-new'),
]

peoplemanagement/peoplemanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peoplemanagement/user/urls.py
from django.conf.urls import url
from django.urls  import path
from . import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', user_views.register, name='register'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.activate, name='activate'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='user/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='user/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='user/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('load-provinces/', user_views.load_province, name='ajax_load_provinces'),  # <-- ajax load provinces ddl
    path('load-cities/', user_views.load_city, name='ajax_load_cities'),  # <-- ajax load cities ddl
]

peoplemanagement/user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.utils import timezone
from django.utils.translation import gettext as _
from django.core.validators import MaxValueValidator, MinValueValidator
from master.models import Country, Province, City, Tribe, Major, Gender
import datetime
from django.core.validators import RegexValidator

def current_year():
    return datetime.date.today().year

def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)
    
def year_choices():
    return [(r,r) for r in range(1991, datetime.date.today().year+1)]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    tribe = models.ForeignKey(Tribe, on_delete=models.SET_NULL, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,14}$', message="Phone number must be entered in the format: '+6281297126699' or 081297126699. Up to 14 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=14, null=True)
    ktp_address = models.TextField(null=True)
    current_address = models.TextField(null=True)
    major = models.ForeignKey(Major, on_delete=models.SET_NULL, null=True)
    class_of = models.IntegerField(choices=year_choices(), validators=[MinValueValidator(1991), max_value_current_year], null=True)
    birth_date = models.DateField(default=timezone.now)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        # super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

peoplemanagement/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from master.models import Province, City
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    def __init__(self   , *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='form-group col-md-6 mb-0'),
                Column('last_name', css_class='form-group col-md-6 mb-0'),
            ),
            Row(
                Column('username', css_class='form-group col-md-12 mb-0')
            ),
            Row(
                Column('email', css_class='form-group col-md-12 mb-0')
            ),
            Row(
                Column('password1', css_class='form-group col-md-12 mb-0')
            ),Row(
                Column('password2', css_class='form-group col-md-12 mb-0')
            ),
            HTML('<div class="form-group">'),
            HTML('<button class="btn btn-primary btn-user btn-block" type="submit">Register Account</button>'),
            HTML('</div>')
        )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]

class ProfileUpdateForm(forms.ModelForm):
    def __init__(self   , *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.attrs['class'] = 'datepicker'
        self.fields['province'].queryset = Province.objects.none()
        self.fields['city'].queryset = City.objects.none()
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                
                self.fields['province'].queryset = Province.objects.filter(country_id=country_id).order_by('province_desc')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Province queryset
        elif self.instance.country != None:
            self.fields['province'].queryset = self.instance.country.province_set.order_by('province_desc')
        else:
            pass

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(province_id=province_id).order_by('city_desc')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.province != None:
            self.fields['city'].queryset = self.instance.province.city_set.order_by('city_desc')
        else:
            pass
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('phone_number', css_class='form-group col-md-12 mb-0'),
            ),
            Row(
                Column('ktp_address', css_class='form-group col-md-6 mb-0'),
                Column('current_address', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            HTML('<legend class="border-bottom">Date of Birth</legend>'),
            Row(
                Column('country', css_class='form-group col-md-4 mb-0'),
                Column('province', css_class='form-group col-md-4 mb-0'),
                Column('city', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('birth_date', css_class='form-group col-md-4 mb-0'),
                Column('tribe', css_class='form-group col-md-4 mb-0'),
                Column('gender', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            HTML('<legend class="border-bottom">Education</legend>'),
            Row(
                Column('major', css_class='form-group col-md-6 mb-0'),
                Column('class_of', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            HTML('<legend class="border-bottom">Profile Picture</legend>'),
            'image',
            HTML('<div class="form-group">'),
            HTML('<button class="btn btn-primary btn-user" type="submit">Update</button>'),
            HTML('</div>')
        )

    class Meta:
        model = Profile
        fields = [
            'country',
            'province',
            'city',
            'tribe',
            'gender',
            'phone_number',
            'ktp_address',
            'current_address',
            'major',
            'class_of',
            'birth_date',
            'image'
            ]
        # labels = {
        # 'country': 'country of birth'
        # }

peoplemanagement/user/views.py
from django.shortcuts import render, redirect 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from master.models import Province, City

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # form.save()
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('user//user_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request, f'We have sent you an email, please confirm your email address to complete registration')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'user//register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile) 

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'user/profile.html', context)

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, 'user//user_active_complete.html')
    else:
        return render(request, 'user//user_active_invalid.html')

def load_province(request):
    country_id = request.GET.get('country')
    if country_id == '':
        country_id = 0
    provinces = Province.objects.filter(country=country_id).order_by('province_desc')
    return render(request, 'master/provinces_ddl.html', {'provinces': provinces})

def load_city(request):
    province_id = request.GET.get('province')
    if province_id == '':
        province_id = 0
    cities = City.objects.filter(province=province_id).order_by('city_desc')
    return render(request, 'master/cities_ddl.html', {'cities': cities})

peoplemanagement/user/templates/user/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ikatan Mahasiswa Minangkabau Gunadarma</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-6 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-12">
                                {% if messages %}
                                {% for message in messages %}
                                {% if message.tags == 'error' %}
                                <div class="dalign-items-center justify-content-between mb-4">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {% else %}
                                <div class="dalign-items-center justify-content-between mb-4">
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                            </div>
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-primary btn-user btn-block"
                                                type="submit">Login</button>
                                        </div>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'register' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

peoplemanagement/user/templates/user/logout.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ikatan Mahasiswa Minangkabau Gunadarma</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-6 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">You have benn logged out!</h1>
                                    </div>
                                    <div class="alert alert-info">
                                        <a href="{% url 'login' %}">Log In Again</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

peoplemanagement/user/templates/user/password_reset.html
{% comment %} {% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
        </div>
    </form>
</div>
{% endblock content %} {% endcomment %}

{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-6 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">

                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-primary btn-user btn-block"
                                                type="submit">Reset Password</button>
                                        </div>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'register' %}">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'login' %}">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

peoplemanagement/user/templates/user/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info col-md-12">
        Your password has been set. <a href="{% url 'login' %}">Sign In Here</a>
    </div>
{% endblock content %}

peoplemanagement/user/templates/user/password_reset_confirm.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ikatan Mahasiswa Minangkabau Gunadarma</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-6 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">

                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Reset Password</h1>
                                    </div>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-primary btn-user btn-block" type="submit">Reset Password</button>
                                        </div>
                                    </form>
                                    <hr>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

peoplemanagement/user/templates/user/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% comment %} <div class="d-sm-flex align-items-center justify-content-between mb-4 col-md-12">
    <h1 class="h3 mb-0 text-gray-800">My Profile</h1>
</div> {% endcomment %}
<div class="card shadow mb-4 col-md-12">
  <div class="card-header py-3">
    <div class="col-md-4"  style="text-align:center">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>

  </div>
  <div class="card-body">
    <form method="POST" enctype="multipart/form-data" id="profileForm"
      data-provinces-url="{% url 'ajax_load_provinces' %}" data-cities-url="{% url 'ajax_load_cities' %}">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Personal Info</legend>
        {{ u_form|crispy }}
        {% crispy p_form %}
        <!-- {{ p_form|crispy }} -->
      </fieldset>
      <!-- <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div> -->
    </form>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $(document).ready(function () {
    $("#id_country").change(function () {
      var url = $("#profileForm").attr("data-provinces-url"); // get the url of the `load_provinces` view
      var countryId = $(this).val(); // get the selected country ID from the HTML input

      $.ajax({ // initialize an AJAX request
        url: url, // set the url of the request (= localhost:8000/..../load-province/)
        data: {
          'country': countryId // add the country id to the GET parameters
        },
        success: function (data) { // `data` is the return of the `load_provinces` view function
          $("#id_province").html(
            data); // replace the contents of the province input with the data that came from the server
        }
      });
    });

    $("#id_province").change(function () {
      var url = $("#profileForm").attr("data-cities-url"); // get the url of the `load_cities` view
      var provinceId = $(this).val(); // get the selected province ID from the HTML input

      $.ajax({ // initialize an AJAX request
        url: url, // set the url of the request (= localhost:8000/..../master/load-cities/)
        data: {
          'province': provinceId // add the province id to the GET parameters
        },
        success: function (data) { // `data` is the return of the `load_cities` view function
          $("#id_city").html(
            data); // replace the contents of the city input with the data that came from the server
        }
      });
    });
  })
</script>
{% endblock content%}

peoplemanagement/user/templates/user/user_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}